### ISSUE TITLE
Select venore town in create character 

### ISSUE THREAD

**Issue by carlosjfernandes** [gordonbay/capernia-ots-datapack#31]
Bug.

**Capture**: `http://i.imgur.com/51cClPS.jpg`

**Comment by gordonbay** [comment]
Character creation is done through mysql inclusion which is selected through web interface so there is nothing that Capernia project can do abou this. The bug that you are showing on this image was fixed some time ago and was caused by wrong Venore's coordinates.

**This issue report is not respecting [the rules ](https://github.com/gordonbay/capernia-ots-datapack/wiki/Issues) on issue post and ill be closed and locked.**
